image: Visual Studio 2017

configuration:
  - Release
  - Debug

platform:
  - x64
  - Win32

environment:
  # VS VERSION IN CMAKE STYLE
  matrix:
    - VSVERSION: "15 2017"
    - VSVERSION: "14 2015"

cache:
  - C:\Users\Appveyor\.conan -> appveyor.yml
  - c:\.conan -> appveyor.yml
  - '%LOCALAPPDATA%\pip\Cache -> appveyor.yml'
  - C:\miktex-repository -> appveyor.yml


init:
  - cmake --version
  - perl --version
  - msbuild /version

install:
  # Static url: https://github.com/MiKTeX/miktex/issues/321#issuecomment-496286866
  # The setup is small enough, and does not need to be cached
  - appveyor DownloadFile  https://miktex.org/download/win/miktexsetup-x64.zip
  - 7z e miktexsetup-x64.zip
  - miktexsetup.exe --local-package-repository=C:\miktex-repository --package-set=essential download
  - miktexsetup.exe --local-package-repository=C:\miktex-repository --package-set=essential --shared install
  - refreshenv
  - pip install conan
  - ps: |
     "[requires]
      libxml2/2.9.8@bincrafters/stable
      winflexbison/2.5.16@bincrafters/stable" | Out-File -Encoding ASCII -FilePath conanfile.txt
  - conan install . -g virtualrunenv --build missing
  - activate_run.bat

before_build:
  - if "%platform%"=="Win32" ( set "CMAKE_GENERATOR_NAME=Visual Studio %VSVERSION%" )
  - if "%platform%"=="x64" ( set "CMAKE_GENERATOR_NAME=Visual Studio %VSVERSION% Win64")
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_GENERATOR_NAME%" ..

build:
  project: "build\\PACKAGE.vcxproj"
  parallel: false

test_script:
  - msbuild "testing\tests.vcxproj" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
# Disabled building document due to unreliable MikTeX installation
#  - cmake -G "%CMAKE_GENERATOR_NAME%" -D build_doc=ON ..
#  - msbuild "doc\docs.vcxproj" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
