image: Visual Studio 2017

configuration:
  - Release
  - Debug

platform:
  - x64
  - Win32

environment:
  # VS VERSION IN CMAKE STYLE
  matrix:
    - VSVERSION: "15 2017"
    - VSVERSION: "14 2015"

init:
  - cmake --version
  - perl --version
  - msbuild /version

install:
  - ps: Invoke-WebRequest https://github.com/lexxmark/winflexbison/releases/download/v2.5.15/win_flex_bison-2.5.15.zip -OutFile flex.zip
  - 7z x flex.zip -oC:\deps\flex
  - ps: Invoke-WebRequest https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs924/gs924w32.exe -OutFile gswin32c.exe
  - gswin32c /S /D=C:\deps\ghostscript
  - ps: if($env:platform -eq "x64") { Invoke-WebRequest https://miktex.org/download/win/miktexsetup-x64.zip -OutFile miktexsetup.zip }
  - ps: if($env:platform -eq "Win32") { Invoke-WebRequest https://miktex.org/download/win/miktexsetup-x86.zip -OutFile miktexsetup.zip }
  - 7z x miktexsetup.zip -oC:\tmpmiktex
  - C:\tmpmiktex\miktexsetup --local-package-repository=C:\temp\miktex --package-set=basic download
  - C:\tmpmiktex\miktexsetup --verbose --local-package-repository=C:\temp\miktex --package-set=basic install
  - refreshenv
  - pip install conan
  - conan install libxml2/2.9.8@bincrafters/stable -g virtualrunenv
  - activate_run.bat
  - set "PATH=%PATH%;C:\deps\ghostscript\bin;C:\deps\flex"

before_build:
  - if "%platform%"=="Win32" ( set "CMAKE_GENERATOR_NAME=Visual Studio %VSVERSION%" )
  - if "%platform%"=="x64" ( set "CMAKE_GENERATOR_NAME=Visual Studio %VSVERSION% Win64")
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_GENERATOR_NAME%" ..

build:
  project: "build\\PACKAGE.vcxproj"
  parallel: false

test_script:
  - msbuild "testing\tests.vcxproj" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmake -G "%CMAKE_GENERATOR_NAME%" -D build_doc=ON ..
#  - msbuild "doc\docs.vcxproj" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
